#define DHT_PIN_DATA      PIN_PD2
#define S7SEG_PIN_DIG1    PIN_PA0
#define S7SEG_PIN_DIG2    PIN_PA1
#define S7SEG_PIN_DIG3    PIN_PA2
#define S7SEG_PIN_DIG4    PIN_PA3
#define S7SEG_PIN_A       PIN_PD7
#define S7SEG_PIN_B       PIN_PC2
#define S7SEG_PIN_C       PIN_PC3
#define S7SEG_PIN_D       PIN_PC4
#define S7SEG_PIN_E       PIN_PC5
#define S7SEG_PIN_F       PIN_PC6
#define S7SEG_PIN_G       PIN_PC7
#define S7SEG_PIN_DECIMAL PIN_PD6
#define Button1           PIN_PB6
#define Button2           PIN_PB4
#define Button3           PIN_PB5
#define Button4           PIN_PB7
#define SW1               PIN_PB0
#define SW2               PIN_PB1
#define SW3               PIN_PB2
#define SW4               PIN_PB3
#define LDR               PIN_PA4 //photoresistor
#define POT1              PIN_PA6
#define LED4              PIN_PA5
#define RGBRed            PIN_PD3
#define RGBGreen          PIN_PD4
#define RGBBlue           PIN_PD5
#define Buzzer            PIN_PA7
